name: ci-golang.workflow #Nome
on: [push] #Em que momento rodar o processo CI, nesse caso no push
jobs: #Quais jobs executar
  check-application: #Nome do primeiro job
    runs-on: ubuntu-latest #Onde eu quero rodar, ultima vers찾o ubuntu
    steps: #passo a passo a ser seguido - As actions s찾o reposit처rios github
      - uses: actions/checkout@v2 #baixa os arquivos na maquina ubuntu
      - uses: actions/setup-go@v2 #Configura um ambiente para rodar GO Lang
        with:
          go-version: 1.15 #Vers찾o 1.15 do GO lang
      - run: go test #Run roda um comando
      - run: go run math.go